Footer 1409
Nina-Antoniuk/event-booster pull request #14
Opened 2021-09-14 17:38 UTC by denyuneedtoknow

2021-09-14 18:49 UTC, Nina-Antoniuk requested changes

2021-09-14 18:49 UTC, Nina-Antoniuk commented on src/sass/components/_buttonUp.scss
> +.buttonUp {
щоб підвищити читабельність кода зміни трохи порядок властивостей http://sadcitizen.me/code-guide/

2021-09-14 18:49 UTC, Nina-Antoniuk commented on src/index.html
> -    <link rel="preconnect" href="https://fonts.googleapis.com">
ти видалив шрифти?

2021-09-14 21:29 UTC, denyuneedtoknow commented on src/index.html
> -    <link rel="preconnect" href="https://fonts.googleapis.com">
та ніби ні, спеціально принаймі точно не видаляв...

2021-09-14 21:29 UTC, denyuneedtoknow commented on src/sass/components/_buttonUp.scss
> +.buttonUp {
ок, тут ясно

2021-09-15 06:10 UTC, denyuneedtoknow commented on src/sass/components/_buttonUp.scss
> +.buttonUp {
поправив порядок властивостей у _footer.scss _buttonUp.scss

2021-09-15 07:01 UTC, Nina-Antoniuk approved these changes

2021-09-15 07:01 UTC, merged